services:
  robot-server-sim:
    container_name: robot_server_sim
    profiles: [ "sim" ]
    image: robot_server
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/bus/usb:/dev/bus/usb
    network_mode: "host"
    environment:
      - REAL_ROBOT=false
      - ROBOT_TYPE=interbotix_rover # can be interbotix_arm, interbotix_rover or ur
      - DISPLAY=${DISPLAY}
      - ROS_MASTER_URI=http://localhost:11311
    privileged: true
    stdin_open: true
    tty: true

  robot-server-real:
    container_name: robot_server_real
    profiles: [ "real" ]
    image: robot_server
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/bus/usb:/dev/bus/usb
    network_mode: "host"
    environment:
      - REAL_ROBOT=true
      - ROBOT_TYPE=interbotix_rover # can be interbotix_arm, interbotix_rover or ur
      - DISPLAY=${DISPLAY}
      - ROS_MASTER_URI=http://locobot:11311 # change if not using locobot
      - ROSLAUNCH_ARGS=robot_model:=locobot_wx250s gui:=false server_port:=55555 real_robot:=true
    privileged: true
    stdin_open: true
    tty: true
